name: Create Docker Container

on: 
  push:
    paths-ignore:
      - 'k8_/app_service_ingress.yaml' 

permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout

jobs:
  mlops-container:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
      
    steps:
        # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          
      - name: List Files
        run: ls -l

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # replaced with OIDC process no need to store secrets in github actions
          role-to-assume: arn:aws:iam::579989520040:role/github_actions  
          aws-region: eu-north-1
      
      - name: Install DVC
        run: pip install dvc[s3]
        
      - name: fetch sklearn_model sklearn_pipeline pipeline_features
        run: |
          # dvc pull src/project/prod/prod_artifacts/feat_pipeline.pkl.dvc 
          # dvc pull src/project/prod/prod_artifacts/feature_name.pkl.dvc 
          dvc pull src/project/prod/prod_artifacts/random_forest_model.dvc 

      - name: List Files
        run: ls -l src/project/prod/prod_artifacts
        
      
        # build the Docker container
      - name: Build container
        run: |
          docker build -t mlops:app-${{ github.run_number }} . --progress=plain --no-cache
     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  

      - name: Push2ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-north-1

          image: mlops:app-${{ github.run_number }} 
              
      
      #update the deployment file so that Argocd can track changes in the deployment file
      - name: List Files
        run: |
          ls -l
          pwd 




  modifygit:
    needs: mlops-container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          persist-credentials: false  # Important: Disable default GitHub credentials, adding this made the workflow work 
      - name: modify the deployment file
        run: |
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_NAME
            git checkout main
            git pull origin main
            echo "----- Current Directory -----"
            pwd
            echo ""
  
            echo "----- current deploy file data -----"
            cat k8_/app_service_ingress.yaml
            echo ""
  
            echo "----- Run number: $RUN_NUMBER -----"
            echo "Run number: $RUN_NUMBER"
            echo ""
            
            echo "----- Replace the image tag in the deployment file -----"
            sed -i "s|579989520040.dkr.ecr.eu-north-1.amazonaws.com/mlops:app-[0-9]\+|579989520040.dkr.ecr.eu-north-1.amazonaws.com/mlops:app-$RUN_NUMBER|g" k8_/app_service_ingress.yaml
            echo ""
  
            echo "----- Updated deploy file data -----"
            cat k8_/app_service_ingress.yaml
            echo ""
  
            echo "----- git status -----"
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/o-Senpai-o/MLOPs_workflow.git
            git add *
            git commit -m 'Done  by Github Actions  Job change manifest: ${{ github.run_number }}'
            git push origin main
        env:
            GIT_NAME: ${{ secrets.GIT_NAME }}
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
            RUN_NUMBER: ${{ github.run_number }}
            GIT_EMAIL : ${{ secrets.GIT_EMAIL }}